feat: 메인페이지, 머쓱이 생성페이지 기능 구현
prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun pull request #105
Opened 2023-09-19 05:32 UTC by from1to2

## 🧩 이슈 번호 
- close #70

## ✅ 작업 사항 
메인페이지

- [ ]  queries 폴더 커스텀 훅 만들기
- [ ]  mainpage 컴포넌트에서 훅을 이용하여 데이터 보여주기
- [ ]  합의된 JSON 객체 parsing 후, 출력
- [ ]  postCard 공통 컴포넌트 선택된 모든 포스트 정보 출력
- [ ]  postCard 공통 컴포넌트 선택된 이미지 출력,
- [ ]  로그인 되지 않은 경우, 머쓱이 생성페이지 이동 불가
- [ ]  로그인된 유저가 포스트 클릭 시, 해당 상세페이지로 이동 구현
- [ ]  포스트 머쓱이 이미지 크기 조정

머쓱이 생성 페이지

- [ ]  useMutation Hook 생성
- [ ]  button event 적용
- [ ]  API 요청 코드 작성
- [ ]  postman test
- [ ]  머쓱이 생성페이지 모든 input default value 설정
- [ ]  머쓱이 생성페이지 -> post(상세페이지) 이동 구현
- [ ]  post(상세페이지) merge 후, 정상 렌더링 되는지 확인
- [ ]  로그인되지 않은 유저는 머쓱이 생성페이지로 이동이 불가능 (기능구현)
- [ ]  머쓱이 이미지 클릭 시, 머쓱이 이미지 변경

## 👩‍💻 공유 포인트 및 논의 사항 
메인페이지 개수 필터링과 메세지 개수에 따른 출력,
반응형 구현이 필요합니다.

머쓱이 생성페이지 이미지 2번 클릭 오류 해결이 필요합니다. 전체 UI 크기 조정이 필요합니다. 반응형 구현이 필요합니다.

2023-09-19 05:37 UTC, juyeon-park requested changes
고생하셨습니다!

2023-09-19 05:37 UTC, juyeon-park commented on src/pages/Newpost/index.tsx
> +                const title = JSON.stringify({
P2: 따로 함수로 빼주는게 보기 좋을 것 같아요!!

2023-09-19 05:37 UTC, juyeon-park commented on src/pages/Main/index.tsx
> +            if (!user && !storage('session').getItem(AUTH_TOKEN, null)) {
삼항 연산자로 더 짧게 해도 좋을 것 같아요 👍 👍

2023-09-19 06:10 UTC, bbearcookie requested changes
고생하셨습니다~~

2023-09-19 06:10 UTC, bbearcookie commented on src/pages/Main/index.tsx
>            }}
P2:
아하.. 버튼 클릭 시 로그인 상황에 따라서 다른 페이지로 리다이렉션하는 방식이군요! 😮
그런데 만약 어떤 사용자가 로그인이 되지 않은 상태에서 버튼을 통한 인터랙션이 아니라 브라우저의 URL에 직접 `/newpost` 라는 주소를 입력하게 되면 머쓱이 생성 페이지로 접근이 가능하게 되는 문제가 발생할 것 같아요!

그래서 버튼의 인터랙션에서 로그인 상태를 검사하기보다는, 페이지 컴포넌트에서 렌더링이 발생할 시점에 로그인 상태를 검사해서 리다이렉션해주는 방식이 더 적합할 듯 싶은데 호수님은 어떻게 생각하시는지 궁금해요! 😊

2023-09-19 06:10 UTC, bbearcookie commented on src/pages/Main/index.tsx
> +                    }}
요 부분도 비슷한 맥락입니다!
추가적으로, onClick 동작을 JSX로 직접적으로 정의하기보다 컴포넌트 내에 이벤트 핸들러 함수를 하나 만들어서 만드는 것도 가독성에 도움이 될 수 있겠다는 생각을 했어요! 😊

2023-09-19 06:10 UTC, bbearcookie commented on src/pages/Newpost/index.tsx
> +      console.log('선택한 머쓱이미지는', musseukImage);
요 부분은 아마 아직 작업중인 부분이셔서 테스트하는 과정에 콘솔이 남아있는 것 같은데요!
나중에 기능이 완성된다면 지워주시는 것도 좋겠네요! 😊

2023-09-19 06:10 UTC, bbearcookie commented on src/pages/Newpost/index.tsx
> +  const handlemusseukIntroduce = (event: ChangeEvent<HTMLTextAreaElement>) => {
P5:
요 부분은 사소하지만 musseuk이 대문자여야 할 것 같네요! 😊
`handleMusseukIntroduce`

2023-09-19 07:11 UTC, Howon-Shin requested changes
수고하셨습니다~

2023-09-19 07:11 UTC, Howon-Shin commented on src/apis/queryKeys.ts
> +    detail: (id: number) => ['posts', 'detail', id] as const
P4:
기존 키를 지우신 이유가 있나요?
id는 16진수 숫자긴 한데 number로는 처리가 안되는 것 같아서 저는 string으로 넣었었습니다!

2023-09-19 07:11 UTC, Howon-Shin commented on src/components/PostCard/index.tsx
> +        />
P5:
저는 제 페이지 constants 폴더에 
```tsx
import MusseukDefault from '@/assets/images/musseuk_default.png';
import MusseukHeart from '@/assets/images/musseuk_heart.png';
import MusseukHood from '@/assets/images/musseuk_hood.png';
import MusseukLaptop from '@/assets/images/musseuk_laptop.png';
import MusseukSemicolon from '@/assets/images/musseuk_semicolon.png';

export const MUSSEUK_IMAGE = {
  [MUSSEUK_IMAGE_NAME.DEFAULT]: MusseukDefault,
  [MUSSEUK_IMAGE_NAME.HEART]: MusseukHeart,
  [MUSSEUK_IMAGE_NAME.HOOD]: MusseukHood,
  [MUSSEUK_IMAGE_NAME.LAPTOP]: MusseukLaptop,
  [MUSSEUK_IMAGE_NAME.SEMICOLON]: MusseukSemicolon
} as const;
```
이런 식으로 객체로 선언해서 이미지 파일을 관리했는데 필요하시면 공통 constants 폴더로 옮겨서 사용하는 것도 좋을 것 같아요!

2023-09-19 07:11 UTC, Howon-Shin commented on src/pages/Main/index.tsx
> +                    musseukContent={JSON.parse(slideContent.title).musseukIntroduce}
P3:
query 함수 내부에서 parse해서 가져오는 게 더 안전할 것 같습니다!

2023-09-19 07:11 UTC, Howon-Shin commented on src/pages/Newpost/index.tsx
> +      { title, musseukImage, CHANNEL_ID },
P3:
stringify도 mutation 내부에서 하면 편할 것 같아요!

2023-09-19 08:48 UTC, Howon-Shin requested changes

2023-09-19 08:48 UTC, Howon-Shin commented on src/apis/queries/useGetPostsInfoQuery.ts
> +  return useQuery<ChannelResponse[]>({
P1:
api의 응답 타입이 잘못 설정되어있는 것 같습니다.
`ChannelResponse`는 채널 정보나 채널 목록을 요청할 때 나오는 응답이고
지금 `/posts/channel/{channelID}`는 응답으로 `PostResponse[]`를 사용해야 할 것 같습니다!
![image](https://github.com/prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun/assets/54025398/64a9aecc-bbd3-48fc-999e-ab0b2fe3700c)

2023-09-19 08:48 UTC, Howon-Shin commented on src/apis/types.ts
> +  comments: CommentResponse[];
위 이슈로 해당 타입 수정도 불필요할 것 같습니다!

2023-09-19 08:54 UTC, from1to2 commented on src/components/PostCard/index.tsx
>  export type Props = {
export 키워드는 필요없는 것 같네요! 👍

2023-09-19 08:54 UTC, from1to2 commented on src/pages/Main/index.tsx
> +  // console.log(data);
data를 확인하기 위한 용도로 잠시 사용하였습니다!

2023-09-19 08:54 UTC, from1to2 commented on src/pages/Main/index.tsx
>            }}
useEffect를 생각해보았는데, url을 통해 접근했을 때 동일한 결과가 나와서 고민중입니다 🤔

2023-09-19 08:56 UTC, from1to2 commented on src/pages/Main/index.tsx
> +                    }}
따로 함수를 만들 경우, 공통 컴포넌트의 onclick 함수의 return type값을 || 을 통해 2개의 결과 타입을 주는 방법이 생각났는데, 가능할지 모르겠습니다 🤔

2023-09-19 08:57 UTC, from1to2 commented on src/apis/mutations/useNewPostMutation.ts
> +    }
기존 mutations문으로 참고하면서 작성한 코드 부분입니다! 비우지 않고 querykey를 임의의 값으로 넣으면 될까요??

2023-09-19 09:01 UTC, from1to2 commented on src/apis/queryKeys.ts
> +    detail: (id: number) => ['posts', 'detail', id] as const
처음에 posts에서 제가 생각했을 때 필요한 부분만 설정을 하였는데, users와 같이 detail, search도 추가로 필요할까요? 필요하다면 어떤 이유에서 필요할까요? 🤔

2023-09-19 09:04 UTC, Howon-Shin commented on src/apis/mutations/useNewPostMutation.ts
> +    }
signOut의 onMutate 함수를 참고하신 것 같은데, 해당 코드는 로그아웃 시 저장된 유저 데이터를 지워버리는 기능 같습니다.

새 포스트를 생성하는 api니까 `onMutate`는 지우고
```tsx
onSuccess: () => {
      queryClient.invalidateQueries(queryKey.posts.all);
    }
```
로 포스트 데이터를 최신화 시켜주는게 좋을 것 같아요!

2023-09-19 09:31 UTC, Howon-Shin commented on src/apis/queryKeys.ts
> +    detail: (id: number) => ['posts', 'detail', id] as const
지금 detail은 포스트 상세 페이지에서 가져온 포스트 데이터의 키로 사용하고 있습니다.
수정된 posts.detail 키를 사용하면 타입 때문에 오류가 날 것 같아요!

search는 프로필 페이지에서 사용할 거라고 생각해서 만들어둔 쿼리키 입니다!

2023-09-19 09:31 UTC, Howon-Shin commented on src/apis/queryKeys.ts
> +    detail: (id: number) => ['posts', 'detail', id] as const
P3:

생각해보니 `useGetPostInfoQuery`에서 `posts.all`을 쿼리 키로 쓰고 있는데 나중에 invalidate 시킬 때 `post.detail`도 초기화되니 비효율적일 것 같습니다.
`useGetPostInfoQuery`에는 `posts.list` 로 새로 만들어서 설정하고 search와는 연동되게 설정하는 게 좋을 것 같네요!
```tsx
posts: {
  all: ['posts'] as const,
  detail: (id: string) => ['posts', 'detail', id] as const, // 포스트 상세 페이지
  list: ['posts', 'lists'] as const, // 메인페이지
  search: (userId: string) => ['posts', 'lists', userId] as const // 프로필 페이지
}
```
정도면 포스트 관련돼서 필요한 쿼리 키는 모두 커버될 것 같습니다.

2023-09-19 11:26 UTC, from1to2 commented on src/apis/queryKeys.ts
> +    detail: (id: number) => ['posts', 'detail', id] as const
usePostDetailQuery.ts에서 queryKey: queryKey.posts.detail(id), 이런식으로 사용하는군요! 데이터 캐싱을 위해 사용하는데, 쿼리 키 구성을 정확히 어떻게 하면 좋을지 고민이 되네요 🤔

2023-09-20 07:01 UTC, Eosdia submitted a review, later dismissed
수고하셨습니다~~

2023-09-20 14:17 UTC, juyeon-park approved these changes
코드리뷰 수정하느라 고생하셨어요! 👍 👍

2023-09-20 14:21 UTC, merged