feat: 포스트 페이지 에러 바운더리 추가
prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun pull request #167
Opened 2023-09-24 16:56 UTC by Howon-Shin

## 🧩 이슈 번호 
- close #166

## ✅ 작업 사항 
- 에러바운더리로 포스트 페이지를 감쌌어요.

## 👩‍💻 공유 포인트 및 논의 사항 
- withAsyncBoundary로 감싸려다 배경 처음에 안 뜨는 게 좀 별로인 것 같아서 ErrorBoundary를 사용했습니다.

2023-09-24 17:17 UTC, bbearcookie approved these changes
고생하셨습니다~~

2023-09-24 17:40 UTC, juyeon-park requested changes
데이터 로딩 에러 페이지 너무 좋습니다!

2023-09-24 17:40 UTC, juyeon-park commented on packages/web/src/pages/Post/ErrorFallback.tsx
> +import { Flex, Button, Heading, Text } from '@chakra-ui/react';
404페이지를 보이게 하는 것보다 데이터 로딩 관련된 에러 컴포넌트를 따로 만드셨군요!! 너무 좋습니다 😄 다른 페이지에서도 쓸 수 있게 Post 페이지 내부가 아닌 상위 component폴더로 이동하는 것은 어떤가요??

2023-09-24 18:19 UTC, bbearcookie commented on packages/web/src/pages/Post/ErrorFallback.tsx
> +import { Flex, Button, Heading, Text } from '@chakra-ui/react';
오~ 좋네요! 👍👍

추가적으로 다른 페이지에서의 재사용성을 위해서 window.location.reload 로 페이지를 리프레쉬하는 방법 대신에 QueryErrorResetBoundary 로 네트워크 요청을 다시 시도하게끔 하는 것도 좋은 방법일 것 같아요!

https://beomy.github.io/tech/react/tanstack-query-v4/#errorboundary

2023-09-25 01:58 UTC, Howon-Shin commented on packages/web/src/pages/Post/ErrorFallback.tsx
> +import { Flex, Button, Heading, Text } from '@chakra-ui/react';
수정했습니다! 👍

2023-09-25 05:51 UTC, bbearcookie approved these changes

2023-09-25 06:09 UTC, juyeon-park approved these changes
고생하셨습니다!

2023-09-25 06:09 UTC, merged