feat: 포스트 페이지 UI 구현
prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun pull request #36
Opened 2023-09-10 14:39 UTC by Howon-Shin

## 🧩 이슈 번호 
- close #12 

## ✅ 작업 사항 
- post page 의 기본 레이아웃 설정
- 머쓱이 클릭에 따라 댓글의 위치 설정하도록 구현
- 머쓱이 크기에 따라 댓글의 크기도 변형되도록 구현

## 👩‍💻 공유 포인트 및 논의 사항 
<img width="1440" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun/assets/54025398/8e6206a9-d8ce-494f-b0f1-b479d074a010">

머쓱이가 로딩 실패했을 경우를 생각해야해요.
일단 크기는 로딩 성공 시와 동일하도록 해야 댓글이 정상적으로 출력될 것 같아요

2023-09-10 17:46 UTC, bbearcookie approved these changes
고생하셨습니다~~ 😊

2023-09-10 17:56 UTC, juyeon-park reviewed
고생하셨습니다! 컴포넌트로 너무 잘 구분하신것 같아요 🙂🙂

2023-09-10 17:56 UTC, juyeon-park commented on src/pages/Post/components/ListButton.tsx
> +    <Button backgroundColor="green01" color="white" size="lg" _hover={{ backgroundColor: 'green03' }} {...props}>
#37 를 참고하면 프로젝트에서 공통적으로 사용하는 버튼 색상을 colorSchema로 만들었습니다. colorSchema에 기본적으로 backgroundColor, hoverColor, activeColor가 설정되어있어서 따로 지정해주지 않으셔도 됩니다! 밑의 코드처럼 변경해주시면 됩니다.🙂🙂
```suggestion
    <Button colorScheme="primary" size="lg" {...props}>
```

2023-09-10 17:57 UTC, juyeon-park requested changes
고생하셨습니다! 컴포넌트로 너무 잘 구분하신것 같아요 🙂🙂

2023-09-11 05:46 UTC, from1to2 commented
수고하셨습니다 호원님! 👍

2023-09-11 06:57 UTC, closed without merging