Feature/58 main page newpost
prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun pull request #67
Opened 2023-09-12 10:04 UTC by from1to2

## 🧩 이슈 번호 
- close #58

## ✅ 작업 사항 
<메인페이지>
    -   페이지네이션 스타일 변경
     -  카드 위치 변경
     -  불필요 여백 제거
 <머쓱이 생성페이지>
     -  불필요 여백 제거
     -  선택아이콘 바 생성
     -  아이콘 선택
 <기타 >
    -  기타 스타일 수정
    -  메인페이지 불필요 폴더 제거
    -  공통 카드 컴포넌트 위치 변경 (커밋 참고함)

## 👩‍💻 공유 포인트 및 논의 사항 
  -  반응형 구현이 필요합니다.
  -  머쓱 생성페이지 아이콘 선택 수정이 필요합니다.
  -  머쓱 생성페이지 테이블 추가가 필요합니다.

2023-09-12 13:43 UTC, Howon-Shin requested changes
탁자 이미지는 지워도 될 것 같습니다😆

2023-09-12 14:55 UTC, bbearcookie requested changes

2023-09-12 14:55 UTC, bbearcookie commented on src/pages/Main/index.tsx
> +import swiper from './swiper.css';
P5:
같은 디렉토리에 `./swiper.css` 라는 파일이 존재하지 않는 것 같아서 삭제되어야 할 구문일까요?? 🧐

2023-09-12 14:55 UTC, bbearcookie commented on src/pages/Main/index.tsx
> +                <PostCard
P3:
children 을 prop으로 전달받지 않는 컴포넌트같은 경우에는 명시적으로 바로 바로 닫아주시는 것도 좋을 것 같아요! 😊

```tsx
<PostCard {...} />
```

2023-09-12 14:55 UTC, bbearcookie commented on src/pages/Main/index.tsx
> +              <div style={{ marginLeft: '4rem', marginBottom: '3.5rem' }}>
P1:
요소에 `style` 속성으로 인라인 스타일을 부여하는 경우에는 항상 새롭게 요소를 렌더링하게 되는데요! 지금같은 상황에서는 정적인 스타일을 부여하고 있음에도 불구하고 매번 새롭게 불필요한 렌더링이 발생하게 되어요! 😢

(https://velog.io/@zero_mountain/ReactStyle-%EC%9D%B8%EB%9D%BC%EC%9D%B8%EC%8A%A4%ED%83%80%EC%9D%BC%EC%97%90-%EA%B4%80%ED%95%98%EC%97%AC)

차크라 UI를 활용하고 있는만큼 `Box` 와 같은 컴포넌트에 부여할 수 있는 스타일 관련 Prop을 부여하는 방식이 좋을 것 같아요!

2023-09-12 14:55 UTC, bbearcookie commented on src/pages/Main/index.tsx
> +      <Box bgColor="color(display-p3 0.9765 0.9765 0.9569);">&nbsp;</Box>
`&nbsp;` 의 역할은 어떤 역할일까요?? 🧐

2023-09-12 18:15 UTC, bbearcookie requested changes

2023-09-12 18:15 UTC, bbearcookie commented on src/pages/Newpost/index.tsx
> +              <Box _hover={{ border: '0.3rem solid #72D988', borderRadius: '10px' }} width="50rem" height="auto">
P1:
아하! 요소가 hover 될 때마다 border 영역이 새롭게 생겨서 들쑥날쑥한 현상이 생겼던거였군요! 😮
기본 border 사이즈를 지정해주면 어느정도 완화가 되는 것 같아요!

```suggestion
              <Box
                  border="0.3rem solid transparent"
                  _hover={{ border: '0.3rem solid #72D988', borderRadius: '10px' }}
                  width="50rem"
                  height="auto">
                  <Image p="0.5rem 0 0.5rem 0" objectFit="fill" marginTop="0.7rem" src={Musseuk} alt="Musseuk" />
              </Box>
```

2023-09-12 18:44 UTC, Eosdia reviewed
고생하셨습니다! 탁자 이미지는 저의 웃음벨 입니다..
theme 에 있는 색상이랑 chakra 컴포넌트를 적극 활용하시는게 좋을 것 같습니다!

2023-09-12 18:44 UTC, Eosdia commented on src/pages/Newpost/index.tsx
> +        <Box p="2rem" margin="auto" w="42%" textAlign="center">
P3:
Box 컴포넌트를 사용하는 것 보다는 Container, Stack, Grid, Flex,... 등 명시적으로 알 수 있는 컴포넌트를 
사용하는게  더 도움이 될 것 같습니다!

2023-09-12 18:44 UTC, Eosdia commented on src/pages/Newpost/index.tsx
> +            </Flex>
P3:
컴포넌트화 해서 재사용할 수 있을것 같은데 혹시 이미지 크기가 다른 문제때문 일까요?
Image 에 width, height 를 주고 objectFit 을 cover 로 하면 이미지 크기가 비슷해 보일것 같아요!
Grid 컴포넌트도 같이 사용하시면 레이아웃에 도움이 될 것 같습니다!

2023-09-13 04:23 UTC, from1to2 commented on src/pages/Main/index.tsx
> +      <Box bgColor="color(display-p3 0.9765 0.9765 0.9569);">&nbsp;</Box>
Box 컴포넌트 이용 시, 하단에 빈공간이 생기는 문제로 임시적으로 배경색을 적용하기 위해 작성한 구문입니다!

2023-09-13 04:41 UTC, from1to2 commented on src/pages/Newpost/index.tsx
> +            </Flex>
컴포넌트화도 좋은 방법이겠군요! objectFit cover 방법도 다시한번 고려해보겠습니다! Grid 컴포넌트 방법도 있군요! 👍

2023-09-13 04:42 UTC, from1to2 commented
피드백 적용 모두 완료하였습니다!

2023-09-13 04:57 UTC, Howon-Shin approved these changes

2023-09-13 05:27 UTC, bbearcookie approved these changes
고생하셨습니다~~

2023-09-13 05:33 UTC, juyeon-park approved these changes
고생하셨습니다😮😮

2023-09-13 06:14 UTC, merged