feat: 포스트 페이지 API 연결
prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun pull request #72
Opened 2023-09-13 09:24 UTC by Howon-Shin

## 🧩 이슈 번호 
- close #60

## ✅ 작업 사항 
- 포스트 페이지에 내용을 가져오기 위해 `usePostDetailQuery`를 구현했어요.
- API에서 받아온 응답을 실제 사용할 데이터로 가공하기 위해 `@/apis/utils`를 만들고 `parsePost` 함수를 구현했어요.
- `parsePost` 함수 내에서 Author와 Comment 데이터 가공을 위해 `parseUser`, `parseComment` 함수도 구현했어요.
- 실제 사용할 데이터들의 타입은 `@/types/index.ts` 에 작성했어요.
- 포스트 페이지에서 작성자 여부에 따라 조건부 UI를 구현했어요.

## 👩‍💻 공유 포인트 및 논의 사항 
- query에서 데이터를 가공하고 내려주면 좋을 것 같아서 parse 함수를 query 함수 내부에서 사용했는데 괜찮을까요?
- `User`의 `fullName` 나 `Post`의 `title` 필드처럼 JSON 형태로 넣었어야 하는 필드에 일반 string을 넣었다면 포스트 페이지에서 오류가 나요. 어느 필드에 어떤 JSON을 넣어야 하는지 논의가 필요할 것 같아요.

2023-09-13 15:10 UTC, bbearcookie requested changes
고생하셨습니다~~
타입에 대한 부분을 어느정도 정리해주셨군요! 👍👍
내일 오프라인에서 다 같이 모여서 타입에 대한 의논을 같이 하면서, 동시에 이 PR에서 타입 내용을 수정해서 머지한다면 좋겠다는 생각이 들었어요!

2023-09-13 15:10 UTC, bbearcookie commented on src/types/index.ts
> +export interface customCommentComment {
P3:
인터페이스이다보니 파스칼 케이스로 작성하는 네이밍이 좋지 않을까요??
추가적으로 Comment가 두 번 반복되고 있는 네이밍이라 `CustomComment` 정도로도 괜찮을 것 같다는 생각이 들었어요!

2023-09-13 15:10 UTC, bbearcookie commented on src/types/index.ts
> +  _id: string;
P3:
이 부분은 `customCommentComment` 타입과 합쳐도 괜찮지 않을까요?
각 코멘트도 결국은 자신의 `_id` 정보를 갖고 있게 되기 때문에요!

자세하게는 다 같이 내일 만나서 타입에 대해 의논해보는 것도 좋겠네요!! 😁

2023-09-13 15:10 UTC, bbearcookie commented on src/apis/utils/parseUser.ts
와~~ 각각의 데이터를 파싱하는 유틸 함수를 만드신 부분 엄청 좋네요!! 😁👍👍

API 서버로부터 날라오는 날 것의 데이터로부터, 우리 서버에서 사용되는 형태의 필드로 변환하는 로직을 명확하게 파악할 수 있어서 좋은 것 같습니다 😊

데이터 파싱 로직을 분리해놓았으니, 서버로부터 어떤 데이터가 날라올지 모르는 상황에 우리 서비스에서 타입 에러가 나지 않도록 기본 값을 넣어놓는다던가, 데이터의 타입을 정제하고 예외를 방지하는 로직을 작성하는 것에도 수월하겠다는 생각이 들었어요!

2023-09-13 19:23 UTC, juyeon-park reviewed
고생하셨습니다👍👍 유틸함수 따봉👍👍

2023-09-13 19:23 UTC, juyeon-park commented on src/apis/queryKeys.ts
> +    search: (userId: string) => ['posts', 'search', userId] as const
이 search 쿼리키는 언제 필요한건가요?? 개인정보 페이지에서 자신이 만든 머쓱이들을 보여줘야할때 필요한 경우일까요??

2023-09-13 19:23 UTC, juyeon-park commented on src/apis/utils/parseUser.ts
동감합니다!! 타입 관련된 회의 진행 후 리팩토링할때 저도 이렇게 파싱하는 유틸함수를 만들어봐야겠네요. 참고하겠습니다👍👍

2023-09-14 02:04 UTC, from1to2 commented on src/apis/utils/parseUser.ts
utill 함수 이용 너무 좋네요! 👍 👍  동감합니다!!

2023-09-14 02:13 UTC, Howon-Shin commented on src/types/index.ts
> +export interface customCommentComment {
comment 데이터의 comment 필드를 JSON으로 사용하는 거라 CommentComment 라고 지었는데 조금 이상한 느낌일까요?
파스칼은 계속 헷갈리네요 😅

2023-09-14 02:15 UTC, Howon-Shin commented on src/apis/queryKeys.ts
> +    search: (userId: string) => ['posts', 'search', userId] as const
넵 그때 필요할 것 같아서 일단 만들어만 놨습니다. 실제 구현하실 분이 수정하시면 될 것 같아요 😙

2023-09-14 07:18 UTC, Howon-Shin commented
type 논의한 것 다시 적용했습니다.

## ✅ 작업 사항 <!-- 가능한 구체적으로 작성해주세요 -->
- type을 논의한 대로 수정했습니다.
- 파싱 함수 내부에서 JSON 파싱 에러 시 기본 값을 내려주도록 구현했습니다.

2023-09-14 07:21 UTC, bbearcookie approved these changes
고생하셨습니다~~

2023-09-14 07:21 UTC, from1to2 commented on src/types/index.ts
> +}
Post 타입 확인하였습니다!

2023-09-14 07:29 UTC, merged