feat: 검색 페이지 구현
prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun pull request #73
Opened 2023-09-13 14:05 UTC by juyeon-park

## 🧩 이슈 번호 
- close #63
- close #64

## ✅ 작업 사항 
- body에 bgColor 통일
- 검색 페이지 UI 구현
- 헤더에서 사용자 검색 시 해당 이름의 사용자가 출력되도록 api 구현
- 검색 결과 페이지로 이동시 Input 초기화를 위해 react-hook-form의 reset함수 사용
- UserCard에 실제 서버 data 연결
- 검색어를 입력해서 onSubmit 핸들러 발생시 useQuery 호출하도록 refetch 사용

## 👩‍💻 공유 포인트 및 논의 사항 
오프라인에서 JSON형태로 오지 않는 초기 생성 데이터들을 어떻게 처리할지 논의해봐야합니다.
-> 강사님께 서버 데이터 초기화 요청하기 or 예외처리 만들기

2023-09-13 15:35 UTC, bbearcookie requested changes
고생하셨습니다~~

2023-09-13 15:35 UTC, bbearcookie commented on src/pages/Search/components/UserCard/index.tsx
> +      onClick={() => navigate(`/profile/${name}`)}>
이 부분은 name 이 아니라 User 모델의 `_id` 값이 들어가야 할 것 같지만 우선 타입에 대한 논의 이후에 작업할 수 있는 부분이겠군요!

2023-09-13 18:56 UTC, juyeon-park commented on src/pages/Search/components/UserCard/index.tsx
> +      onClick={() => navigate(`/profile/${name}`)}>
id가 들어가도록 수정완료했습니다!

2023-09-13 18:58 UTC, juyeon-park commented on src/components/header/index.tsx
> +    await setKeyword(value.keyword);
헉 setState는 Promise 반환형태가 아니라는 것을 기억하지 못하고 동기적으로 작동하게 하려고 단순구현만 한 것 같네요. useQuery 관련된 정보들을 찾아보면서 굳이 header에서 useQuery를 호출하지 않고 search 페이지가 따로 있기 때문에 search 페이지에서 useQuery함수를 호출하도록 수정했습니다!

2023-09-14 02:07 UTC, from1to2 commented on src/theme/index.tsx
> +  },
body 요소 색상 bg01로 처리해주셨네요!! 👍 👍

2023-09-14 02:31 UTC, Howon-Shin approved these changes
고심하신게 느껴지네요 👍

2023-09-14 02:31 UTC, Howon-Shin commented on src/pages/Search/components/UserCard/index.tsx
> +  comment: string[];
P4;

post랑 comment는 length만 prop으로 받아와도 될 것 같아요!

2023-09-14 05:02 UTC, juyeon-park commented on src/pages/Search/components/UserCard/index.tsx
> +  comment: string[];
넵 수정하겠습니다!!

2023-09-14 05:02 UTC, juyeon-park commented on src/theme/index.tsx
> +  },
👍 👍

2023-09-14 05:02 UTC, bbearcookie approved these changes
고생하셨습니다~~

2023-09-14 05:02 UTC, merged